# Generated by Django 3.1.4 on 2020-12-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesTBL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_salary', models.CharField(max_length=20)),
                ('emp_city', models.CharField(max_length=30)),
                ('emp_dob', models.DateField()),
                ('emp_mobile_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'EmployeesTBL',
            },
        ),
    ]
